version: '3.5'

services:
  proxy:
    container_name: tor-proxy
    image: peterdavehello/tor-socks-proxy:latest
    restart: always
    ports:
      - 9150:9150/tcp
    networks:
      - my-network
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_db_data:/data
    networks:
      - my-network
  asynqmon:
    container_name: asynqmon
    image: hibiken/asynqmon
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - my-network
    environment:
      REDIS_ADDR: redis:6379
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: pg
        POSTGRES_USER: pg
    volumes:
        - postgres:/var/lib/postgresql/data

networks:
  my-network:

volumes:
  redis_db_data:
    external: false
  postgres: