pipelines:
  pipeline1:
    - task: task1
    - task: task2
    - task: task3

tasks:
  task1:
    description: "Queue Processors"
    command:
      - go run main.go
  task2:
    description: "Queue Scheduler"
    command:
      - go run scheduler/main.go
  task3:
    description: "REST API"
    command:
      - go run rest/main.go
